# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92543d88a6f119ff1996ad5c47a82ec32bc3f50a4b1ab4ea865c6b5130fefbec9fe5c476cf2dd4ddf5a010bed7a1fe745a10d5acc282fa0cf684e485b98557ab

test:
  secret_key_base: 841ee64df8b7f3f04af1daac1fb022322021cb557acca6a37a1004cbab577fb3b65b24012907c30a18d494aafca3ea06abd7f087c23548aea955c97ec829a22d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
